/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'xmc4700_mdk' 
 * Target:  'flash_cached' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "XMC4700.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* Infineon::Device:Startup@3.0.0 */
#define RTE_DEVICE_STARTUP
/* Infineon::Device:XMClib:GPIO@2.2.0 */
#define RTE_DEVICE_XMCLIB_GPIO
/* Infineon::Device:XMClib:SCU@2.2.0 */
#define RTE_DEVICE_XMCLIB_SCU
/* Infineon::Device:XMClib:UART@2.2.0 */
#define RTE_DEVICE_XMCLIB_UART


#endif /* RTE_COMPONENTS_H */
