/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'xmc4700_mdk' 
 * Target:  'webserver' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "XMC4700.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS-Compiler:TTY:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_TTY                   /* CMSIS-Compiler TTY */
#define RTE_CMSIS_Compiler_TTY_Custom            /* CMSIS-Compiler TTY: Custom */
/* ARM::CMSIS-View:Event Recorder&DAP@1.6.0 */
#define RTE_CMSIS_View_EventRecorder
#define RTE_CMSIS_View_EventRecorder_DAP
/* ARM::RTOS&FreeRTOS:Config&FreeRTOS@11.3.0 */
#define RTE_RTOS_FreeRTOS_CONFIG        /* RTOS FreeRTOS Config for FreeRTOS API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.3.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.3.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.3.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* Infineon::Device:Startup@3.0.0 */
#define RTE_DEVICE_STARTUP
/* Infineon::Device:XMClib:ETH_MAC@2.2.0 */
#define RTE_DEVICE_XMCLIB_ETH_MAC
/* Infineon::Device:XMClib:ETH_PHY@2.2.0 */
#define RTE_DEVICE_XMCLIB_ETH_PHY
/* Infineon::Device:XMClib:GPIO@2.2.0 */
#define RTE_DEVICE_XMCLIB_GPIO
/* Infineon::Device:XMClib:SCU@2.2.0 */
#define RTE_DEVICE_XMCLIB_SCU
/* Infineon::Device:XMClib:UART@2.2.0 */
#define RTE_DEVICE_XMCLIB_UART


#endif /* RTE_COMPONENTS_H */
